[package]
name = "Chip8-Emulator"
version = "0.1.0"
authors = ["Matthew Pletcher <matt.pletch@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.10.4"
rand = "0.3.14"